"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InlineJSComponents = void 0;
const inlinejs_1 = require("@benbraide/inlinejs");
const component_1 = require("./core/component");
const code_1 = require("./core/code");
const overlay_1 = require("./extended/overlay");
const xhr_1 = require("./extended/xhr");
const xhr_select_1 = require("./extended/xhr-select");
const image_1 = require("./dom/image");
const action_1 = require("./dom/form/action");
const sketch_1 = require("./canvas/sketch");
const sketch_history_1 = require("./canvas/sketch-history");
const sketch_freehand_1 = require("./canvas/sketch-freehand");
const sketch_line_1 = require("./canvas/sketch-line");
const sketch_rectangle_1 = require("./canvas/sketch-rectangle");
const sketch_circle_1 = require("./canvas/sketch-circle");
const sketch_brush_1 = require("./canvas/sketch-brush");
const sketch_eraser_1 = require("./canvas/sketch-eraser");
const sketch_export_1 = require("./canvas/sketch-export");
function InlineJSComponents() {
    (0, inlinejs_1.WaitForGlobal)().then(() => {
        (0, component_1.ComponentCompact)();
        (0, code_1.CodeCompact)();
        (0, overlay_1.OverlayCompact)();
        (0, xhr_1.XhrCompact)();
        (0, xhr_select_1.XhrSelectCompact)();
        (0, image_1.ImageCompact)();
        (0, action_1.FormActionCompact)();
        (0, sketch_1.SketchCompact)();
        (0, sketch_history_1.SketchHistoryCompact)();
        (0, sketch_freehand_1.SketchFreehandCompact)();
        (0, sketch_line_1.SketchLineCompact)();
        (0, sketch_rectangle_1.SketchRectangleCompact)();
        (0, sketch_circle_1.SketchCircleCompact)();
        (0, sketch_brush_1.SketchBrushCompact)();
        (0, sketch_eraser_1.SketchEraserCompact)();
        (0, sketch_export_1.SketchExportCompact)();
    });
}
exports.InlineJSComponents = InlineJSComponents;
